development:
  adapter: mysql2
  encoding: utf8
  database: remotely_dev
  pool: 5
  username: <%= ENV['DEV_DB_USER'] %>
  socket: <%= ENV['DEV_DB_SOCKET'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: remotely_test
  pool: 5
  username: <%= ENV['DEV_DB_USER'] %>
  socket: <%= ENV['DEV_DB_SOCKET'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: remotely_prod
  pool: 5
  username: <%= ENV['PROD_DB_USER'] %>
  password: <%= ENV['PROD_DB_PASSWD'] %>
  host: <%= ENV['PROD_DB_HOST'] %>